### ISSUE TITLE
Use spikeinterfaces

### ISSUE THREAD

**Issue by TheChymera** [TheChymera/neuralynx_nwb#2]
```python
from spikeinterface.extractors import NeuralynxRecordingExtractor

obj = NeuralynxRecordingExtractor("dir_path")
```

**Comment by CodyCBakerPhD** [comment]
This also enables you to use NeuroConv tools to reduce the amount of code you need to maintain for this.

All the NeuroConv tools also come equipped with iterative write and automated compression (default is just "gzip" level 4), both of which are highly recommended for working with data pipelines that could ever exceed ~10 GB or so.

If you encounter any questions or issues with NeuroConv, please feel free to [let us know](https://github.com/catalystneuro/neuroconv/issues/new/choose).

### Highest level of NeuroConv would be to use the [NeuralynxDataInterface](https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/recording/neuralynx.html)

To create an example NWB file showing the default structure and automatically extracted metadata when converting from Neuralynx I'd just modify that showcase to

```python
from datetime import datetime
from dateutil import tz
from pathlib import Path
from neuroconv.datainterfaces import NeuralynxRecordingInterface

folder_path = f".../neuralynx/Cheetah_v5.7.4/original_data"
interface = NeuralynxRecordingInterface(folder_path=folder_path, verbose=False)

# Extract what metadata we can from the source files
metadata = interface.get_metadata()
# session_start_time is required for conversion. If it cannot be inferred
# automatically from the source files you must supply one.
session_start_time = datetime(2020, 1, 1, 12, 30, 0, tzinfo=tz.gettz("US/Pacific"))
metadata["NWBFile"].update(session_start_time=session_start_time)  # other key/value pairs of this dict are passed directly to pynwb.NWBFile(...)

interface.run_conversion(nwbfile_path="save/to/path.nwb", metadata=metadata, stub_test=True)  # stub_test for fast testing
```

The interface use SpikeInterface under the hood, but the point is to make the users life as easy as possible by just taking as input the path, and as output the NWB file.

For more greater customization or control, see below.



### At a lower level of direct interaction with SpikeInterface, use our [SpikeInterface conversion tools](https://neuroconv.readthedocs.io/en/main/api/tools.spikeinterface.html)

In particular, you ought to be able to just call

```python
from neuroconv.tools.spikeinterface import write_recording

write_recording(recording=your_recording_object, nwbfile_path="/save/to/path.nwb")
```

Or if you want to pass in an existing `nwbfile` in-memory, calling

```python
from neuroconv.tools.spikeinterface import add_electrical_series

add_electrical_series(recording=your_recording_object, nwbfile=nwbfile)
```

will modify it in-place.

**Comment by CodyCBakerPhD** [comment]
After looking into this a bit more on our side, I'd strongly recommend try to use the DataInterface approach.

We recently refactored the metadata for that interface so that we utilize as much as possible from the source files: https://github.com/catalystneuro/neuroconv/blob/main/tests/test_on_data/test_metadata/test_neuralynx_metadata.py

**Comment by TheChymera** [comment]
@CodyCBakerPhD is the object which I would be passing to `write_recording()` the interface itself?

**Comment by CodyCBakerPhD** [comment]
@TheChymera Sorry for the delayed repsonse, I've been away at a conference

> object which I would be passing to write_recording() the interface itself?

I updated my code above to make the usage more obvious


> Also, is there a way to handle the streams automatically?

Drat, doesn't look like we expose that at the interface level yet. Past testing data may have only had a single stream

The `NeuralynxRecordingExtractor` however does, I believe it's named `stream_name` (and one of those long names it lists in the message or just the `stream_id` (one of the 3 integers)

I do wish those streams had better names; do you know what each stream represents? Especially that one with 2kHz rate?



P.S.: I don't have access to DANDI slack ATM but it notified me that you messaged a question - as I recall, "icephys" = "**i**ntra**c**ellular **e**lectro**phys**iology" (patch clamp, etc) and "ecephys" = "**e**xtra**c**ellular **e**lectro**phys**iology" (electrodes from probes/arrays outside the cell)

**Comment by CodyCBakerPhD** [comment]
That would make sense then

I'm not sure how to disambiguate the raw vs. thresholded streams since they have the type of signature, but maybe you can find some property of the data that can distinguish it

The thresholded data would be included in the 'processed' submodule using the extra key/value `write_as="processed"` in [`write_recording`](https://neuroconv.readthedocs.io/en/main/api/tools.spikeinterface.html#neuroconv.tools.spikeinterface.spikeinterface.write_recording)

The wheel series will need to written manually using a `pynwb.TimeSeries` - do you have a way to map the aux channel Volt signal (assuming that's how it's stored) into turns/radians/other physical units?

**Comment by TheChymera** [comment]
@CodyCBakerPhD well, I'll have to think about stream auto-detection, but for now, should I try to use `neuroconv` or `spikeinterface`? I'm still not sure how to write object using `from neuroconv.datainterfaces import NeuralynxRecordingInterface`. In your example above it seems like the reader interface is only used for the metadata. Or am I missing something?

**Comment by CodyCBakerPhD** [comment]
> should I try to use neuroconv or spikeinterface?

As I mention, the `NeuralynxRecordingInterface` doesn't expose `stream_id` or `stream_name` yet, can make a fix but would take a little bit.

Interfaces do the same thing as described in the section entitled 'At a lower level of direct interaction with SpikeInterface...' from the [above comment](https://github.com/TheChymera/neuralynx_nwb/issues/2#issuecomment-1379370137), plus a bit of extra metadata stuff.

But for an initial draft conversion, fine to just try the `tools` to see how it looks in the file and adjust from there
